#pragma once
namespace ZJCS
{
	namespace Common
	{
		#pragma region 准发
		const string sqlinsertpresend = "INSERT INTO UACS_PLAN_MATPERMITSEND_ACK (COIL_NO1,COIL_NO2,COIL_NO3,EQU_NO) VALUES (:pMAT,:pPresend,:pMT,:pEQU)";
		const string sqlselpresendmat = "SELECT * FROM UACS_PLAN_MATPERMITSEND_ACK WHERE COIL_NO1=:pMAT";
		const string sqlupdatepresendmat = "UPDATE UACS_PLAN_MATPERMITSEND_ACK SET COIL_NO2= :pPresend ,COIL_NO3=:pMT,EQU_NO=:pEQU WHERE COIL_NO1=:pMAT";
		const string sqlgetprosendgetack = "SELECT RES_FLAG,MESSAGE FROM UACS_PLAN_MATPERMITSEND_ACK WHERE COIL_NO1 =:pMAT";
		#pragma endregion
		#pragma region 用户登录
		const string sqlSelPSW="SELECT * FROM UACS_USER_INF WHERE USERID=:pUsr";
		const string sqlSelPrivilege = "SELECT PRIVILAGE FROM UACS_USER_INF WHERE USERID = :pUserNO ";
		#pragma endregion
		#pragma region 入/出库
		const string sqlSelCarPosINF = "SELECT * FROM UACS_TRUCK_STOWAGE WHERE STOWAGE_ID = :pID ";
		const string sqlSelMaxProcess = "SELECT MAX(STOWAGE_ID) SEQ FROM UACS_TRUCK_STOWAGE WHERE FRAME_NO = :pCarno AND STOWAGE_TYPE=:pWorktype AND CONFIRM_FLAG<>1";
		const string sqlSelMatOnCar = "SELECT * FROM UACS_TRUCK_STOWAGE_DETAIL WHERE STOWAGE_ID = :pID ";
		const string sqlSelIsCarArr = "SELECT * FROM UACS_TRUCK_ARRIVE_LOG WHERE STOWAGE_ID = :pID and FRAME_NO=:pCarno";
		const string sqlSelUpdCarArr = "UPDATE UACS_TRUCK_ARRIVE_LOG SET FRAME_LOCATION =:pPos,YARD_NO=:pYard,ARRIVE_FLAG=:pArrFlag,CONFIR_USERNAME=:pUSE WHERE STOWAGE_ID = :pID and FRAME_NO=:pCarno";
		const string sqlSelInsCarArr = "INSERT INTO UACS_TRUCK_ARRIVE_LOG (STOWAGE_ID,YARD_NO,FRAME_NO,FRAME_LOCATION,ARRIVE_FLAG,CONFIR_USERNAME,CONFIR_TIME) VALUES (:pID,:pYard,:pCarno,:pPos,:pArrFlag,:pUSE,CURRENT TIMESTAMP)";
		const string sqlDelMat = "Delete FROM UACS_TRUCK_STOWAGE_DETAIL WHERE STOWAGE_ID = :pID AND MAT_NO=:pMAT";
		const string sqlScanMat = "SELECT * FROM UACS_PDA_SCAN WHERE MAT_NO = :pMAT AND STOWAGE_ID = :pID";
		const string sqlUpdScanMat = "UPDATE UACS_PDA_SCAN SET SCAN_TYPE=:pType,"
									"EQU_NO=:pPTID,"
									"USERNAME=:pUSER,"
									"MAT_DIRECTION=:pDir,"
									"SLEEVE_LENGTH=:pLen,"
									"PACKAGE_STATUS= :pSta ,"
									"ISUNLOAD=:pIsL "
									"WHERE STOWAGE_ID = :pID and MAT_NO=:pMAT";
		const string sqlInsScanMat = "INSERT INTO UACS_PDA_SCAN (MAT_NO,STOWAGE_ID,SCAN_TYPE,EQU_NO,USERNAME,MAT_DIRECTION,SLEEVE_LENGTH,PACKAGE_STATUS,ISUNLOAD,PROCESS_NO,PT_ACTION_COUNT,COIL_POSITION_7,CAR_NO,PACKING_SPACE) "
									 "VALUES (:pMAT,:pID,:pType,:pPTID,:pUSER,:pDir,:pLen,:pSta,:pIsL,:pPro,:pCou,:pCoil_7,:pCar,:pPark)";
		const string sqlIsMatLoad = "SELECT * FROM UACS_TRUCK_STOWAGE_DETAIL WHERE MAT_NO = :pMAT AND STOWAGE_ID = :pID";		
		const string sqlUpdMatLoad = "UPDATE UACS_TRUCK_STOWAGE_DETAIL SET POS_ON_FRAME=:pPos,"
									 "CONFIRM_FLAG= 1,"
									 "CONFIRM_USERNAME=:pUsr,"
									 "CONFIRM_TIME= CURRENT TIMESTAMP "
									 "WHERE STOWAGE_ID = :pID and MAT_NO=:pMAT";
		const string sqlInsMatLoad = "INSERT INTO UACS_TRUCK_STOWAGE_DETAIL (MAT_NO,STOWAGE_ID,POS_ON_FRAME,CONFIRM_FLAG,CONFIRM_USERNAME,CONFIRM_TIME,STATUS) "
									 "VALUES (:pMAT,:pID,:pPos,1,:pUsr,CURRENT TIMESTAMP,:pSTA)";
		const string sqlInsTruck = "INSERT INTO UACS_TRUCK_STOWAGE (STOWAGE_TYPE,FRAME_NO,FRAME_LOCATION,LOAD_FLAG,REC_TIME,FRAME_DIRECTION,CONFIRM_FLAG) "
									 "VALUES (:pTYPE,:pCar,:pLOC,:pFLAG,CURRENT TIMESTAMP,:pDIR,:pCon)";
		const string sqlSelMatACK = "SELECT * FROM UACS_PDA_SCAN WHERE STOWAGE_ID = :pID ";
		const string sqlSelYard_No = "SELECT UACS_YARDMAP_AREA_DEFINE.YARD_NO FROM UACS_YARDMAP_AREA_DEFINE ,UACS_YARDMAP_VEC_PASSAGE_DEFINE,UACS_TRUCK_STOWAGE "
									 "WHERE UACS_TRUCK_STOWAGE.STOWAGE_ID=:pPos AND "
									 "UACS_YARDMAP_VEC_PASSAGE_DEFINE.VEC_PASSAGE_NO=UACS_TRUCK_STOWAGE.FRAME_LOCATION AND "
									 "UACS_YARDMAP_AREA_DEFINE.AREA_NO=UACS_YARDMAP_VEC_PASSAGE_DEFINE.AREA_NO ";
		const string sqlGetStoAndPos = "SELECT * FROM UACS_PARKING_STATUS WHERE PARKING_NO = :pParkNo";		
		const string sqlUpdPtScanCount="UPDATE UACS_PARKING_STATUS SET PT_ACTION_COUNT=:pCount WHERE PARKING_NO=:pPark";
		const string sqlSelPosDir="SELECT * FROM UACS_HEAD_POSITION_CONFIG WHERE FLAG=:pFlag AND PARKING_NO=:pPark";
		#pragma endregion

		#pragma region 材料信息查询
		const string sqlSelMatINF="SELECT * FROM UACS_PLAN_MATMESSAGE WHERE COIL_NO=:pMAT";
		const string sqlSelMatUnit="SELECT * FROM UACS_YARDMAP_STOCK_DEFINE WHERE MAT_NO=:pMAT";
		const string sqlSelUnitMat="SELECT * FROM UACS_YARDMAP_STOCK_DEFINE WHERE STOCK_NO=:pStock";
		#pragma endregion

		#pragma region 盘库
		const string sqlSelStockMat="SELECT * FROM UACS_YARDMAP_COIL WHERE STOCK_NO LIKE :pCol";
		const string sqlDelStockMat="DELETE FROM UACS_YARDMAP_COIL WHERE STOCK_NO LIKE :pCol";
		const string sqlInsStockMat="INSERT INTO UACS_YARDMAP_COIL (COIL_NO,STOCK_NO,WEIGHT,WIDTH,INDIA,OUTDIA,PACK_FLAG,SLEEVE_WIDTH,COIL_OPEN_DIRECTION,NEXT_UNIT_NO,CONTRACT_NO,ACT_WEIGHT,ACT_WIDTH,UPD_TIME) "
									 "VALUES (:pMAT,:pSto,:pWei,:pWid,:pINDIA,:pOUTDIA,:pPACK,:pSLEEVE,:pDIR,:pNEXT,:pCONT,:pAWE,:pAWI,CURRENT TIMESTAMP)";
		const string sqlInsStockMatPart="INSERT INTO UACS_YARDMAP_COIL (COIL_NO,STOCK_NO,UPD_TIME) VALUES (:pMAT,:pSto,CURRENT TIMESTAMP)";
		const string sqlUpdStockMatPart="UPDATE UACS_YARDMAP_COIL SET STOCK_NO=:pSTOCK WHERE COIL_NO=:pMat";
		const string sqlSelInventoryRecoed="SELECT * FROM UACS_PDA_INVENTORY_HIS WHERE STOCK_NO=:pSto AND EFFECT_FLAG='Y'";
		const string sqlSelDelRecoed="DELETE FROM UACS_PDA_INVENTORY_HIS WHERE MATNO_REAL=:pMat AND EFFECT_FLAG='Y'";
		const string sqlSelGetOriMat="SELECT * FROM UACS_YARDMAP_STOCK_DEFINE WHERE STOCK_NO=:pSto";
		const string sqlUpdInventoryRecoed="UPDATE UACS_PDA_INVENTORY_HIS SET MATNO_REAL=:pMat,"
										   "MATNO_UACS=:pMatOri,"
										   "SCAN_USERID=:pUsr,"
										   "SCAN_TIME=CURRENT TIMESTAMP,"
										   "PTID=:pPTID "
										   "WHERE STOCK_NO=:pSTOCK";
		const string sqlInsInventoryRecoed="INSERT INTO UACS_PDA_INVENTORY_HIS (STOCK_NO,MATNO_UACS,MATNO_REAL,SCAN_USERID,SCAN_TIME,EFFECT_FLAG,PTID) "
										   "VALUES (:pSTOCK,:pMatOri,:pMAT,:pUsr,CURRENT TIMESTAMP,'Y',:pPTID)";
		const string sqlSelInventoryDiff="SELECT * FROM UACS_PDA_INVENTORY WHERE STOCK_NO=:pSTOCK AND CONFIRM_FLAG!=1";
		const string sqlUpdInventoryDiff="UPDATE UACS_PDA_INVENTORY SET MATNO_SYS =:pMatsys,MATNO_REAL=:pMATReal,USERID=:pUSR,REC_TIME=CURRENT TIMESTAMP WHERE STOCK_NO=:pSTOCK";
		const string sqlInsInventoryDiff="INSERT INTO UACS_PDA_INVENTORY (MATNO_SYS,MATNO_REAL,USERID,REC_TIME,STOCK_NO,CONFIRM_FLAG) "
										 "VALUES (:pMatsys,:pMATReal,:pUSR,CURRENT TIMESTAMP,:pSTOCK,0)";
		const string sqlSelDiffStockMat="SELECT * FROM UACS_YARDMAP_COIL WHERE INVENTORY_FLAG!=1";
		#pragma endregion
		#pragma region 出库计划
		const string sqlSelOutPICK="SELECT * FROM UACS_PLAN_L3PICK WHERE DEL_FLAG='I'";
		const string sqlSelOutTRAN="SELECT * FROM UACS_PLAN_L3TRANS WHERE DEL_FLAG='I'";
		const string sqlSelOutL3PRO="SELECT * FROM UACS_PLAN_L3PRODPLAN WHERE DEL_FLAG='I'";
		const string sqlSelOutL2PRO="SELECT * FROM UACS_PLAN_L2PDI_DETAIL ";
		#pragma endregion
	}
}