// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

// <auto-generated>
//
// Generated from file `ProdLine.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>

#ifndef ___________include_clts_slice_ProdLine_h__
#define ___________include_clts_slice_ProdLine_h__

#include <Ice/LocalObjectF.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/StreamF.h>
#include <CltsException.h>
#include <LineTrack.h>
#include <LineL2Plan.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace CLTS
{

class ProdLine;

}

}

namespace CLTS
{

class ProdLine;
bool operator==(const ProdLine&, const ProdLine&);
bool operator<(const ProdLine&, const ProdLine&);

}

namespace IceInternal
{

::Ice::Object* upCast(::CLTS::ProdLine*);
::IceProxy::Ice::Object* upCast(::IceProxy::CLTS::ProdLine*);

}

namespace CLTS
{

typedef ::IceInternal::Handle< ::CLTS::ProdLine> ProdLinePtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::CLTS::ProdLine> ProdLinePrx;

void __read(::IceInternal::BasicStream*, ProdLinePrx&);
void __patch__ProdLinePtr(void*, ::Ice::ObjectPtr&);

}

namespace CLTS
{

class Callback_ProdLine_getExitTracks_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_ProdLine_getExitTracks_Base> Callback_ProdLine_getExitTracksPtr;

class Callback_ProdLine_getEntryTracks_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_ProdLine_getEntryTracks_Base> Callback_ProdLine_getEntryTracksPtr;

class Callback_ProdLine_setExitTracks_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_ProdLine_setExitTracks_Base> Callback_ProdLine_setExitTracksPtr;

class Callback_ProdLine_setEntryTracks_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_ProdLine_setEntryTracks_Base> Callback_ProdLine_setEntryTracksPtr;

}

namespace IceProxy
{

namespace CLTS
{

class ProdLine : virtual public ::IceProxy::Ice::Object
{
public:

    ::CLTS::ExitSaddleTrackSeq getExitTracks()
    {
        return getExitTracks(0);
    }
    ::CLTS::ExitSaddleTrackSeq getExitTracks(const ::Ice::Context& __ctx)
    {
        return getExitTracks(&__ctx);
    }

    ::Ice::AsyncResultPtr begin_getExitTracks()
    {
        return begin_getExitTracks(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getExitTracks(const ::Ice::Context& __ctx)
    {
        return begin_getExitTracks(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getExitTracks(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getExitTracks(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getExitTracks(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getExitTracks(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getExitTracks(const ::CLTS::Callback_ProdLine_getExitTracksPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getExitTracks(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getExitTracks(const ::Ice::Context& __ctx, const ::CLTS::Callback_ProdLine_getExitTracksPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getExitTracks(&__ctx, __del, __cookie);
    }

    ::CLTS::ExitSaddleTrackSeq end_getExitTracks(const ::Ice::AsyncResultPtr&);
    
private:

    ::CLTS::ExitSaddleTrackSeq getExitTracks(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getExitTracks(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::CLTS::EntrySaddleTrackSeq getEntryTracks()
    {
        return getEntryTracks(0);
    }
    ::CLTS::EntrySaddleTrackSeq getEntryTracks(const ::Ice::Context& __ctx)
    {
        return getEntryTracks(&__ctx);
    }

    ::Ice::AsyncResultPtr begin_getEntryTracks()
    {
        return begin_getEntryTracks(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getEntryTracks(const ::Ice::Context& __ctx)
    {
        return begin_getEntryTracks(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getEntryTracks(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getEntryTracks(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getEntryTracks(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getEntryTracks(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getEntryTracks(const ::CLTS::Callback_ProdLine_getEntryTracksPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getEntryTracks(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getEntryTracks(const ::Ice::Context& __ctx, const ::CLTS::Callback_ProdLine_getEntryTracksPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getEntryTracks(&__ctx, __del, __cookie);
    }

    ::CLTS::EntrySaddleTrackSeq end_getEntryTracks(const ::Ice::AsyncResultPtr&);
    
private:

    ::CLTS::EntrySaddleTrackSeq getEntryTracks(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getEntryTracks(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void setExitTracks(const ::CLTS::ExitSaddleTrackSeq& exitTracks)
    {
        setExitTracks(exitTracks, 0);
    }
    void setExitTracks(const ::CLTS::ExitSaddleTrackSeq& exitTracks, const ::Ice::Context& __ctx)
    {
        setExitTracks(exitTracks, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_setExitTracks(const ::CLTS::ExitSaddleTrackSeq& exitTracks)
    {
        return begin_setExitTracks(exitTracks, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setExitTracks(const ::CLTS::ExitSaddleTrackSeq& exitTracks, const ::Ice::Context& __ctx)
    {
        return begin_setExitTracks(exitTracks, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setExitTracks(const ::CLTS::ExitSaddleTrackSeq& exitTracks, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setExitTracks(exitTracks, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setExitTracks(const ::CLTS::ExitSaddleTrackSeq& exitTracks, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setExitTracks(exitTracks, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setExitTracks(const ::CLTS::ExitSaddleTrackSeq& exitTracks, const ::CLTS::Callback_ProdLine_setExitTracksPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setExitTracks(exitTracks, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setExitTracks(const ::CLTS::ExitSaddleTrackSeq& exitTracks, const ::Ice::Context& __ctx, const ::CLTS::Callback_ProdLine_setExitTracksPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setExitTracks(exitTracks, &__ctx, __del, __cookie);
    }

    void end_setExitTracks(const ::Ice::AsyncResultPtr&);
    
private:

    void setExitTracks(const ::CLTS::ExitSaddleTrackSeq&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_setExitTracks(const ::CLTS::ExitSaddleTrackSeq&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void setEntryTracks(const ::CLTS::EntrySaddleTrackSeq& entryTracks)
    {
        setEntryTracks(entryTracks, 0);
    }
    void setEntryTracks(const ::CLTS::EntrySaddleTrackSeq& entryTracks, const ::Ice::Context& __ctx)
    {
        setEntryTracks(entryTracks, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_setEntryTracks(const ::CLTS::EntrySaddleTrackSeq& entryTracks)
    {
        return begin_setEntryTracks(entryTracks, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setEntryTracks(const ::CLTS::EntrySaddleTrackSeq& entryTracks, const ::Ice::Context& __ctx)
    {
        return begin_setEntryTracks(entryTracks, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setEntryTracks(const ::CLTS::EntrySaddleTrackSeq& entryTracks, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setEntryTracks(entryTracks, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setEntryTracks(const ::CLTS::EntrySaddleTrackSeq& entryTracks, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setEntryTracks(entryTracks, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setEntryTracks(const ::CLTS::EntrySaddleTrackSeq& entryTracks, const ::CLTS::Callback_ProdLine_setEntryTracksPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setEntryTracks(entryTracks, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setEntryTracks(const ::CLTS::EntrySaddleTrackSeq& entryTracks, const ::Ice::Context& __ctx, const ::CLTS::Callback_ProdLine_setEntryTracksPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setEntryTracks(entryTracks, &__ctx, __del, __cookie);
    }

    void end_setEntryTracks(const ::Ice::AsyncResultPtr&);
    
private:

    void setEntryTracks(const ::CLTS::EntrySaddleTrackSeq&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_setEntryTracks(const ::CLTS::EntrySaddleTrackSeq&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<ProdLine> ice_context(const ::Ice::Context& __context) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ProdLine*>(_Base::ice_context(__context).get());
    #else
        return dynamic_cast<ProdLine*>(::IceProxy::Ice::Object::ice_context(__context).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ProdLine> ice_adapterId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ProdLine*>(_Base::ice_adapterId(__id).get());
    #else
        return dynamic_cast<ProdLine*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ProdLine> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ProdLine*>(_Base::ice_endpoints(__endpoints).get());
    #else
        return dynamic_cast<ProdLine*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ProdLine> ice_locatorCacheTimeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ProdLine*>(_Base::ice_locatorCacheTimeout(__timeout).get());
    #else
        return dynamic_cast<ProdLine*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ProdLine> ice_connectionCached(bool __cached) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ProdLine*>(_Base::ice_connectionCached(__cached).get());
    #else
        return dynamic_cast<ProdLine*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ProdLine> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ProdLine*>(_Base::ice_endpointSelection(__est).get());
    #else
        return dynamic_cast<ProdLine*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ProdLine> ice_secure(bool __secure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ProdLine*>(_Base::ice_secure(__secure).get());
    #else
        return dynamic_cast<ProdLine*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ProdLine> ice_preferSecure(bool __preferSecure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ProdLine*>(_Base::ice_preferSecure(__preferSecure).get());
    #else
        return dynamic_cast<ProdLine*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ProdLine> ice_router(const ::Ice::RouterPrx& __router) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ProdLine*>(_Base::ice_router(__router).get());
    #else
        return dynamic_cast<ProdLine*>(::IceProxy::Ice::Object::ice_router(__router).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ProdLine> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ProdLine*>(_Base::ice_locator(__locator).get());
    #else
        return dynamic_cast<ProdLine*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ProdLine> ice_collocationOptimized(bool __co) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ProdLine*>(_Base::ice_collocationOptimized(__co).get());
    #else
        return dynamic_cast<ProdLine*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ProdLine> ice_twoway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ProdLine*>(_Base::ice_twoway().get());
    #else
        return dynamic_cast<ProdLine*>(::IceProxy::Ice::Object::ice_twoway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ProdLine> ice_oneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ProdLine*>(_Base::ice_oneway().get());
    #else
        return dynamic_cast<ProdLine*>(::IceProxy::Ice::Object::ice_oneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ProdLine> ice_batchOneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ProdLine*>(_Base::ice_batchOneway().get());
    #else
        return dynamic_cast<ProdLine*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ProdLine> ice_datagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ProdLine*>(_Base::ice_datagram().get());
    #else
        return dynamic_cast<ProdLine*>(::IceProxy::Ice::Object::ice_datagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ProdLine> ice_batchDatagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ProdLine*>(_Base::ice_batchDatagram().get());
    #else
        return dynamic_cast<ProdLine*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ProdLine> ice_compress(bool __compress) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ProdLine*>(_Base::ice_compress(__compress).get());
    #else
        return dynamic_cast<ProdLine*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ProdLine> ice_timeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ProdLine*>(_Base::ice_timeout(__timeout).get());
    #else
        return dynamic_cast<ProdLine*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ProdLine> ice_connectionId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ProdLine*>(_Base::ice_connectionId(__id).get());
    #else
        return dynamic_cast<ProdLine*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    #endif
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace CLTS
{

class ProdLine : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual ::CLTS::ExitSaddleTrackSeq getExitTracks(const ::Ice::Context*) = 0;

    virtual ::CLTS::EntrySaddleTrackSeq getEntryTracks(const ::Ice::Context*) = 0;

    virtual void setExitTracks(const ::CLTS::ExitSaddleTrackSeq&, const ::Ice::Context*) = 0;

    virtual void setEntryTracks(const ::CLTS::EntrySaddleTrackSeq&, const ::Ice::Context*) = 0;
};

}

}

namespace IceDelegateM
{

namespace CLTS
{

class ProdLine : virtual public ::IceDelegate::CLTS::ProdLine,
                 virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual ::CLTS::ExitSaddleTrackSeq getExitTracks(const ::Ice::Context*);

    virtual ::CLTS::EntrySaddleTrackSeq getEntryTracks(const ::Ice::Context*);

    virtual void setExitTracks(const ::CLTS::ExitSaddleTrackSeq&, const ::Ice::Context*);

    virtual void setEntryTracks(const ::CLTS::EntrySaddleTrackSeq&, const ::Ice::Context*);
};

}

}

namespace IceDelegateD
{

namespace CLTS
{

class ProdLine : virtual public ::IceDelegate::CLTS::ProdLine,
                 virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual ::CLTS::ExitSaddleTrackSeq getExitTracks(const ::Ice::Context*);

    virtual ::CLTS::EntrySaddleTrackSeq getEntryTracks(const ::Ice::Context*);

    virtual void setExitTracks(const ::CLTS::ExitSaddleTrackSeq&, const ::Ice::Context*);

    virtual void setEntryTracks(const ::CLTS::EntrySaddleTrackSeq&, const ::Ice::Context*);
};

}

}

namespace CLTS
{

class ProdLine : virtual public ::Ice::Object
{
public:

    typedef ProdLinePrx ProxyType;
    typedef ProdLinePtr PointerType;
    
    virtual ::Ice::ObjectPtr ice_clone() const;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual ::CLTS::ExitSaddleTrackSeq getExitTracks(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getExitTracks(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::CLTS::EntrySaddleTrackSeq getEntryTracks(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getEntryTracks(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void setExitTracks(const ::CLTS::ExitSaddleTrackSeq&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___setExitTracks(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void setEntryTracks(const ::CLTS::EntrySaddleTrackSeq&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___setEntryTracks(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void __write(::IceInternal::BasicStream*) const;
    virtual void __read(::IceInternal::BasicStream*, bool);
// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
    virtual void __write(const ::Ice::OutputStreamPtr&) const;
    virtual void __read(const ::Ice::InputStreamPtr&, bool);
#endif
};

inline bool operator==(const ProdLine& l, const ProdLine& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const ProdLine& l, const ProdLine& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace CLTS
{

template<class T>
class CallbackNC_ProdLine_getExitTracks : public Callback_ProdLine_getExitTracks_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::CLTS::ExitSaddleTrackSeq&);

    CallbackNC_ProdLine_getExitTracks(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CLTS::ProdLinePrx __proxy = ::CLTS::ProdLinePrx::uncheckedCast(__result->getProxy());
        ::CLTS::ExitSaddleTrackSeq __ret;
        try
        {
            __ret = __proxy->end_getExitTracks(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret);
#else
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
#endif
        }
    }

    Response response;
};

template<class T> Callback_ProdLine_getExitTracksPtr
newCallback_ProdLine_getExitTracks(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::CLTS::ExitSaddleTrackSeq&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ProdLine_getExitTracks<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ProdLine_getExitTracksPtr
newCallback_ProdLine_getExitTracks(T* instance, void (T::*cb)(const ::CLTS::ExitSaddleTrackSeq&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ProdLine_getExitTracks<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_ProdLine_getExitTracks : public Callback_ProdLine_getExitTracks_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::CLTS::ExitSaddleTrackSeq&, const CT&);

    Callback_ProdLine_getExitTracks(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CLTS::ProdLinePrx __proxy = ::CLTS::ProdLinePrx::uncheckedCast(__result->getProxy());
        ::CLTS::ExitSaddleTrackSeq __ret;
        try
        {
            __ret = __proxy->end_getExitTracks(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#else
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#endif
        }
    }

    Response response;
};

template<class T, typename CT> Callback_ProdLine_getExitTracksPtr
newCallback_ProdLine_getExitTracks(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::CLTS::ExitSaddleTrackSeq&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ProdLine_getExitTracks<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ProdLine_getExitTracksPtr
newCallback_ProdLine_getExitTracks(T* instance, void (T::*cb)(const ::CLTS::ExitSaddleTrackSeq&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ProdLine_getExitTracks<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_ProdLine_getEntryTracks : public Callback_ProdLine_getEntryTracks_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::CLTS::EntrySaddleTrackSeq&);

    CallbackNC_ProdLine_getEntryTracks(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CLTS::ProdLinePrx __proxy = ::CLTS::ProdLinePrx::uncheckedCast(__result->getProxy());
        ::CLTS::EntrySaddleTrackSeq __ret;
        try
        {
            __ret = __proxy->end_getEntryTracks(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret);
#else
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
#endif
        }
    }

    Response response;
};

template<class T> Callback_ProdLine_getEntryTracksPtr
newCallback_ProdLine_getEntryTracks(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::CLTS::EntrySaddleTrackSeq&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ProdLine_getEntryTracks<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ProdLine_getEntryTracksPtr
newCallback_ProdLine_getEntryTracks(T* instance, void (T::*cb)(const ::CLTS::EntrySaddleTrackSeq&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ProdLine_getEntryTracks<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_ProdLine_getEntryTracks : public Callback_ProdLine_getEntryTracks_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::CLTS::EntrySaddleTrackSeq&, const CT&);

    Callback_ProdLine_getEntryTracks(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CLTS::ProdLinePrx __proxy = ::CLTS::ProdLinePrx::uncheckedCast(__result->getProxy());
        ::CLTS::EntrySaddleTrackSeq __ret;
        try
        {
            __ret = __proxy->end_getEntryTracks(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#else
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#endif
        }
    }

    Response response;
};

template<class T, typename CT> Callback_ProdLine_getEntryTracksPtr
newCallback_ProdLine_getEntryTracks(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::CLTS::EntrySaddleTrackSeq&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ProdLine_getEntryTracks<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ProdLine_getEntryTracksPtr
newCallback_ProdLine_getEntryTracks(T* instance, void (T::*cb)(const ::CLTS::EntrySaddleTrackSeq&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ProdLine_getEntryTracks<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_ProdLine_setExitTracks : public Callback_ProdLine_setExitTracks_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_ProdLine_setExitTracks(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CLTS::ProdLinePrx __proxy = ::CLTS::ProdLinePrx::uncheckedCast(__result->getProxy());
        try
        {
            __proxy->end_setExitTracks(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)();
#else
            (::IceInternal::CallbackNC<T>::callback.get()->*response)();
#endif
        }
    }

    Response response;
};

template<class T> Callback_ProdLine_setExitTracksPtr
newCallback_ProdLine_setExitTracks(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ProdLine_setExitTracks<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ProdLine_setExitTracksPtr
newCallback_ProdLine_setExitTracks(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ProdLine_setExitTracks<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_ProdLine_setExitTracksPtr
newCallback_ProdLine_setExitTracks(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ProdLine_setExitTracks<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ProdLine_setExitTracksPtr
newCallback_ProdLine_setExitTracks(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ProdLine_setExitTracks<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_ProdLine_setExitTracks : public Callback_ProdLine_setExitTracks_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_ProdLine_setExitTracks(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CLTS::ProdLinePrx __proxy = ::CLTS::ProdLinePrx::uncheckedCast(__result->getProxy());
        try
        {
            __proxy->end_setExitTracks(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(CT::dynamicCast(__result->getCookie()));
#else
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(CT::dynamicCast(__result->getCookie()));
#endif
        }
    }

    Response response;
};

template<class T, typename CT> Callback_ProdLine_setExitTracksPtr
newCallback_ProdLine_setExitTracks(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ProdLine_setExitTracks<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ProdLine_setExitTracksPtr
newCallback_ProdLine_setExitTracks(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ProdLine_setExitTracks<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_ProdLine_setExitTracksPtr
newCallback_ProdLine_setExitTracks(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ProdLine_setExitTracks<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ProdLine_setExitTracksPtr
newCallback_ProdLine_setExitTracks(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ProdLine_setExitTracks<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_ProdLine_setEntryTracks : public Callback_ProdLine_setEntryTracks_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_ProdLine_setEntryTracks(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CLTS::ProdLinePrx __proxy = ::CLTS::ProdLinePrx::uncheckedCast(__result->getProxy());
        try
        {
            __proxy->end_setEntryTracks(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)();
#else
            (::IceInternal::CallbackNC<T>::callback.get()->*response)();
#endif
        }
    }

    Response response;
};

template<class T> Callback_ProdLine_setEntryTracksPtr
newCallback_ProdLine_setEntryTracks(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ProdLine_setEntryTracks<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ProdLine_setEntryTracksPtr
newCallback_ProdLine_setEntryTracks(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ProdLine_setEntryTracks<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_ProdLine_setEntryTracksPtr
newCallback_ProdLine_setEntryTracks(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ProdLine_setEntryTracks<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ProdLine_setEntryTracksPtr
newCallback_ProdLine_setEntryTracks(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ProdLine_setEntryTracks<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_ProdLine_setEntryTracks : public Callback_ProdLine_setEntryTracks_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_ProdLine_setEntryTracks(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CLTS::ProdLinePrx __proxy = ::CLTS::ProdLinePrx::uncheckedCast(__result->getProxy());
        try
        {
            __proxy->end_setEntryTracks(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(CT::dynamicCast(__result->getCookie()));
#else
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(CT::dynamicCast(__result->getCookie()));
#endif
        }
    }

    Response response;
};

template<class T, typename CT> Callback_ProdLine_setEntryTracksPtr
newCallback_ProdLine_setEntryTracks(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ProdLine_setEntryTracks<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ProdLine_setEntryTracksPtr
newCallback_ProdLine_setEntryTracks(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ProdLine_setEntryTracks<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_ProdLine_setEntryTracksPtr
newCallback_ProdLine_setEntryTracks(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ProdLine_setEntryTracks<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ProdLine_setEntryTracksPtr
newCallback_ProdLine_setEntryTracks(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ProdLine_setEntryTracks<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
