top_srcdir = ${IPLATURE}

PROGRAM   :=  ../../../Bin/APP_Order
SRCDIRS   := .
include $(IPLATURE)/source/iplature_exegeneral

CXXFLAGS  +=  -I. -I../../../Include/CommonH 
CXXFLAGS  +=  -I../../../Include/iPlature64

LINKWITH  :=  -L $(IPLATURE)/library/ -lPowerTranser $(LINKWITH)




