// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

// <auto-generated>
//
// Generated from file `Archive.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>

#ifndef __tag___Archive_h__
#define __tag___Archive_h__

#include <Ice/LocalObjectF.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/StreamF.h>
#include <tag/TagDefines.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace iPlature
{

class ArchiveInterface;

}

}

namespace iPlature
{

class ArchiveInterface;
bool operator==(const ArchiveInterface&, const ArchiveInterface&);
bool operator<(const ArchiveInterface&, const ArchiveInterface&);

}

namespace IceInternal
{

::Ice::Object* upCast(::iPlature::ArchiveInterface*);
::IceProxy::Ice::Object* upCast(::IceProxy::iPlature::ArchiveInterface*);

}

namespace iPlature
{

typedef ::IceInternal::Handle< ::iPlature::ArchiveInterface> ArchiveInterfacePtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::iPlature::ArchiveInterface> ArchiveInterfacePrx;

void __read(::IceInternal::BasicStream*, ArchiveInterfacePrx&);
void __patch__ArchiveInterfacePtr(void*, ::Ice::ObjectPtr&);

}

namespace iPlature
{

class Callback_ArchiveInterface_ArchiveL1OPC_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_ArchiveInterface_ArchiveL1OPC_Base> Callback_ArchiveInterface_ArchiveL1OPCPtr;

class Callback_ArchiveInterface_ArchiveMD_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_ArchiveInterface_ArchiveMD_Base> Callback_ArchiveInterface_ArchiveMDPtr;

class Callback_ArchiveInterface_ArchiveTimer_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_ArchiveInterface_ArchiveTimer_Base> Callback_ArchiveInterface_ArchiveTimerPtr;

class Callback_ArchiveInterface_EnableArchive_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_ArchiveInterface_EnableArchive_Base> Callback_ArchiveInterface_EnableArchivePtr;

class Callback_ArchiveInterface_EnableAllArchives_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_ArchiveInterface_EnableAllArchives_Base> Callback_ArchiveInterface_EnableAllArchivesPtr;

class Callback_ArchiveInterface_RegisterTimerWatch_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_ArchiveInterface_RegisterTimerWatch_Base> Callback_ArchiveInterface_RegisterTimerWatchPtr;

class Callback_ArchiveInterface_ReReadConfiguration_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_ArchiveInterface_ReReadConfiguration_Base> Callback_ArchiveInterface_ReReadConfigurationPtr;

}

namespace IceProxy
{

namespace iPlature
{

class ArchiveInterface : virtual public ::IceProxy::Ice::Object
{
public:

    void ArchiveL1OPC(const ::iPlature::TAGVALUEMAP& tagPairs)
    {
        ArchiveL1OPC(tagPairs, 0);
    }
    void ArchiveL1OPC(const ::iPlature::TAGVALUEMAP& tagPairs, const ::Ice::Context& __ctx)
    {
        ArchiveL1OPC(tagPairs, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_ArchiveL1OPC(const ::iPlature::TAGVALUEMAP& tagPairs)
    {
        return begin_ArchiveL1OPC(tagPairs, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_ArchiveL1OPC(const ::iPlature::TAGVALUEMAP& tagPairs, const ::Ice::Context& __ctx)
    {
        return begin_ArchiveL1OPC(tagPairs, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_ArchiveL1OPC(const ::iPlature::TAGVALUEMAP& tagPairs, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_ArchiveL1OPC(tagPairs, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_ArchiveL1OPC(const ::iPlature::TAGVALUEMAP& tagPairs, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_ArchiveL1OPC(tagPairs, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_ArchiveL1OPC(const ::iPlature::TAGVALUEMAP& tagPairs, const ::iPlature::Callback_ArchiveInterface_ArchiveL1OPCPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_ArchiveL1OPC(tagPairs, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_ArchiveL1OPC(const ::iPlature::TAGVALUEMAP& tagPairs, const ::Ice::Context& __ctx, const ::iPlature::Callback_ArchiveInterface_ArchiveL1OPCPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_ArchiveL1OPC(tagPairs, &__ctx, __del, __cookie);
    }

    void end_ArchiveL1OPC(const ::Ice::AsyncResultPtr&);
    
private:

    void ArchiveL1OPC(const ::iPlature::TAGVALUEMAP&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_ArchiveL1OPC(const ::iPlature::TAGVALUEMAP&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void ArchiveMD(const ::iPlature::TAGVALUEMAP& tagTimeStamp, const ::iPlature::TAGVALUEMAP& tagPairs, const ::std::string& strTopicName)
    {
        ArchiveMD(tagTimeStamp, tagPairs, strTopicName, 0);
    }
    void ArchiveMD(const ::iPlature::TAGVALUEMAP& tagTimeStamp, const ::iPlature::TAGVALUEMAP& tagPairs, const ::std::string& strTopicName, const ::Ice::Context& __ctx)
    {
        ArchiveMD(tagTimeStamp, tagPairs, strTopicName, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_ArchiveMD(const ::iPlature::TAGVALUEMAP& tagTimeStamp, const ::iPlature::TAGVALUEMAP& tagPairs, const ::std::string& strTopicName)
    {
        return begin_ArchiveMD(tagTimeStamp, tagPairs, strTopicName, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_ArchiveMD(const ::iPlature::TAGVALUEMAP& tagTimeStamp, const ::iPlature::TAGVALUEMAP& tagPairs, const ::std::string& strTopicName, const ::Ice::Context& __ctx)
    {
        return begin_ArchiveMD(tagTimeStamp, tagPairs, strTopicName, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_ArchiveMD(const ::iPlature::TAGVALUEMAP& tagTimeStamp, const ::iPlature::TAGVALUEMAP& tagPairs, const ::std::string& strTopicName, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_ArchiveMD(tagTimeStamp, tagPairs, strTopicName, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_ArchiveMD(const ::iPlature::TAGVALUEMAP& tagTimeStamp, const ::iPlature::TAGVALUEMAP& tagPairs, const ::std::string& strTopicName, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_ArchiveMD(tagTimeStamp, tagPairs, strTopicName, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_ArchiveMD(const ::iPlature::TAGVALUEMAP& tagTimeStamp, const ::iPlature::TAGVALUEMAP& tagPairs, const ::std::string& strTopicName, const ::iPlature::Callback_ArchiveInterface_ArchiveMDPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_ArchiveMD(tagTimeStamp, tagPairs, strTopicName, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_ArchiveMD(const ::iPlature::TAGVALUEMAP& tagTimeStamp, const ::iPlature::TAGVALUEMAP& tagPairs, const ::std::string& strTopicName, const ::Ice::Context& __ctx, const ::iPlature::Callback_ArchiveInterface_ArchiveMDPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_ArchiveMD(tagTimeStamp, tagPairs, strTopicName, &__ctx, __del, __cookie);
    }

    void end_ArchiveMD(const ::Ice::AsyncResultPtr&);
    
private:

    void ArchiveMD(const ::iPlature::TAGVALUEMAP&, const ::iPlature::TAGVALUEMAP&, const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_ArchiveMD(const ::iPlature::TAGVALUEMAP&, const ::iPlature::TAGVALUEMAP&, const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void ArchiveTimer(const ::iPlature::TAGNAMEARRAY& tagNames, const ::iPlature::TAGVALUEMAP& tagPairs)
    {
        ArchiveTimer(tagNames, tagPairs, 0);
    }
    void ArchiveTimer(const ::iPlature::TAGNAMEARRAY& tagNames, const ::iPlature::TAGVALUEMAP& tagPairs, const ::Ice::Context& __ctx)
    {
        ArchiveTimer(tagNames, tagPairs, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_ArchiveTimer(const ::iPlature::TAGNAMEARRAY& tagNames, const ::iPlature::TAGVALUEMAP& tagPairs)
    {
        return begin_ArchiveTimer(tagNames, tagPairs, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_ArchiveTimer(const ::iPlature::TAGNAMEARRAY& tagNames, const ::iPlature::TAGVALUEMAP& tagPairs, const ::Ice::Context& __ctx)
    {
        return begin_ArchiveTimer(tagNames, tagPairs, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_ArchiveTimer(const ::iPlature::TAGNAMEARRAY& tagNames, const ::iPlature::TAGVALUEMAP& tagPairs, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_ArchiveTimer(tagNames, tagPairs, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_ArchiveTimer(const ::iPlature::TAGNAMEARRAY& tagNames, const ::iPlature::TAGVALUEMAP& tagPairs, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_ArchiveTimer(tagNames, tagPairs, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_ArchiveTimer(const ::iPlature::TAGNAMEARRAY& tagNames, const ::iPlature::TAGVALUEMAP& tagPairs, const ::iPlature::Callback_ArchiveInterface_ArchiveTimerPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_ArchiveTimer(tagNames, tagPairs, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_ArchiveTimer(const ::iPlature::TAGNAMEARRAY& tagNames, const ::iPlature::TAGVALUEMAP& tagPairs, const ::Ice::Context& __ctx, const ::iPlature::Callback_ArchiveInterface_ArchiveTimerPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_ArchiveTimer(tagNames, tagPairs, &__ctx, __del, __cookie);
    }

    void end_ArchiveTimer(const ::Ice::AsyncResultPtr&);
    
private:

    void ArchiveTimer(const ::iPlature::TAGNAMEARRAY&, const ::iPlature::TAGVALUEMAP&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_ArchiveTimer(const ::iPlature::TAGNAMEARRAY&, const ::iPlature::TAGVALUEMAP&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void EnableArchive(bool bFlag, const ::iPlature::TAGNAMEARRAY& tagNames)
    {
        EnableArchive(bFlag, tagNames, 0);
    }
    void EnableArchive(bool bFlag, const ::iPlature::TAGNAMEARRAY& tagNames, const ::Ice::Context& __ctx)
    {
        EnableArchive(bFlag, tagNames, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_EnableArchive(bool bFlag, const ::iPlature::TAGNAMEARRAY& tagNames)
    {
        return begin_EnableArchive(bFlag, tagNames, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_EnableArchive(bool bFlag, const ::iPlature::TAGNAMEARRAY& tagNames, const ::Ice::Context& __ctx)
    {
        return begin_EnableArchive(bFlag, tagNames, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_EnableArchive(bool bFlag, const ::iPlature::TAGNAMEARRAY& tagNames, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_EnableArchive(bFlag, tagNames, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_EnableArchive(bool bFlag, const ::iPlature::TAGNAMEARRAY& tagNames, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_EnableArchive(bFlag, tagNames, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_EnableArchive(bool bFlag, const ::iPlature::TAGNAMEARRAY& tagNames, const ::iPlature::Callback_ArchiveInterface_EnableArchivePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_EnableArchive(bFlag, tagNames, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_EnableArchive(bool bFlag, const ::iPlature::TAGNAMEARRAY& tagNames, const ::Ice::Context& __ctx, const ::iPlature::Callback_ArchiveInterface_EnableArchivePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_EnableArchive(bFlag, tagNames, &__ctx, __del, __cookie);
    }

    void end_EnableArchive(const ::Ice::AsyncResultPtr&);
    
private:

    void EnableArchive(bool, const ::iPlature::TAGNAMEARRAY&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_EnableArchive(bool, const ::iPlature::TAGNAMEARRAY&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void EnableAllArchives(bool bFlag)
    {
        EnableAllArchives(bFlag, 0);
    }
    void EnableAllArchives(bool bFlag, const ::Ice::Context& __ctx)
    {
        EnableAllArchives(bFlag, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_EnableAllArchives(bool bFlag)
    {
        return begin_EnableAllArchives(bFlag, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_EnableAllArchives(bool bFlag, const ::Ice::Context& __ctx)
    {
        return begin_EnableAllArchives(bFlag, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_EnableAllArchives(bool bFlag, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_EnableAllArchives(bFlag, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_EnableAllArchives(bool bFlag, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_EnableAllArchives(bFlag, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_EnableAllArchives(bool bFlag, const ::iPlature::Callback_ArchiveInterface_EnableAllArchivesPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_EnableAllArchives(bFlag, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_EnableAllArchives(bool bFlag, const ::Ice::Context& __ctx, const ::iPlature::Callback_ArchiveInterface_EnableAllArchivesPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_EnableAllArchives(bFlag, &__ctx, __del, __cookie);
    }

    void end_EnableAllArchives(const ::Ice::AsyncResultPtr&);
    
private:

    void EnableAllArchives(bool, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_EnableAllArchives(bool, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void RegisterTimerWatch(const ::std::string& strTopicName, const ::iPlature::TAGNAMEARRAY& tagNames, ::Ice::Int nTimerWatchMode, bool bFlag)
    {
        RegisterTimerWatch(strTopicName, tagNames, nTimerWatchMode, bFlag, 0);
    }
    void RegisterTimerWatch(const ::std::string& strTopicName, const ::iPlature::TAGNAMEARRAY& tagNames, ::Ice::Int nTimerWatchMode, bool bFlag, const ::Ice::Context& __ctx)
    {
        RegisterTimerWatch(strTopicName, tagNames, nTimerWatchMode, bFlag, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_RegisterTimerWatch(const ::std::string& strTopicName, const ::iPlature::TAGNAMEARRAY& tagNames, ::Ice::Int nTimerWatchMode, bool bFlag)
    {
        return begin_RegisterTimerWatch(strTopicName, tagNames, nTimerWatchMode, bFlag, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_RegisterTimerWatch(const ::std::string& strTopicName, const ::iPlature::TAGNAMEARRAY& tagNames, ::Ice::Int nTimerWatchMode, bool bFlag, const ::Ice::Context& __ctx)
    {
        return begin_RegisterTimerWatch(strTopicName, tagNames, nTimerWatchMode, bFlag, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_RegisterTimerWatch(const ::std::string& strTopicName, const ::iPlature::TAGNAMEARRAY& tagNames, ::Ice::Int nTimerWatchMode, bool bFlag, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_RegisterTimerWatch(strTopicName, tagNames, nTimerWatchMode, bFlag, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_RegisterTimerWatch(const ::std::string& strTopicName, const ::iPlature::TAGNAMEARRAY& tagNames, ::Ice::Int nTimerWatchMode, bool bFlag, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_RegisterTimerWatch(strTopicName, tagNames, nTimerWatchMode, bFlag, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_RegisterTimerWatch(const ::std::string& strTopicName, const ::iPlature::TAGNAMEARRAY& tagNames, ::Ice::Int nTimerWatchMode, bool bFlag, const ::iPlature::Callback_ArchiveInterface_RegisterTimerWatchPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_RegisterTimerWatch(strTopicName, tagNames, nTimerWatchMode, bFlag, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_RegisterTimerWatch(const ::std::string& strTopicName, const ::iPlature::TAGNAMEARRAY& tagNames, ::Ice::Int nTimerWatchMode, bool bFlag, const ::Ice::Context& __ctx, const ::iPlature::Callback_ArchiveInterface_RegisterTimerWatchPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_RegisterTimerWatch(strTopicName, tagNames, nTimerWatchMode, bFlag, &__ctx, __del, __cookie);
    }

    void end_RegisterTimerWatch(const ::Ice::AsyncResultPtr&);
    
private:

    void RegisterTimerWatch(const ::std::string&, const ::iPlature::TAGNAMEARRAY&, ::Ice::Int, bool, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_RegisterTimerWatch(const ::std::string&, const ::iPlature::TAGNAMEARRAY&, ::Ice::Int, bool, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void ReReadConfiguration()
    {
        ReReadConfiguration(0);
    }
    void ReReadConfiguration(const ::Ice::Context& __ctx)
    {
        ReReadConfiguration(&__ctx);
    }

    ::Ice::AsyncResultPtr begin_ReReadConfiguration()
    {
        return begin_ReReadConfiguration(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_ReReadConfiguration(const ::Ice::Context& __ctx)
    {
        return begin_ReReadConfiguration(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_ReReadConfiguration(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_ReReadConfiguration(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_ReReadConfiguration(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_ReReadConfiguration(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_ReReadConfiguration(const ::iPlature::Callback_ArchiveInterface_ReReadConfigurationPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_ReReadConfiguration(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_ReReadConfiguration(const ::Ice::Context& __ctx, const ::iPlature::Callback_ArchiveInterface_ReReadConfigurationPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_ReReadConfiguration(&__ctx, __del, __cookie);
    }

    void end_ReReadConfiguration(const ::Ice::AsyncResultPtr&);
    
private:

    void ReReadConfiguration(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_ReReadConfiguration(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<ArchiveInterface> ice_context(const ::Ice::Context& __context) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ArchiveInterface*>(_Base::ice_context(__context).get());
    #else
        return dynamic_cast<ArchiveInterface*>(::IceProxy::Ice::Object::ice_context(__context).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ArchiveInterface> ice_adapterId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ArchiveInterface*>(_Base::ice_adapterId(__id).get());
    #else
        return dynamic_cast<ArchiveInterface*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ArchiveInterface> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ArchiveInterface*>(_Base::ice_endpoints(__endpoints).get());
    #else
        return dynamic_cast<ArchiveInterface*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ArchiveInterface> ice_locatorCacheTimeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ArchiveInterface*>(_Base::ice_locatorCacheTimeout(__timeout).get());
    #else
        return dynamic_cast<ArchiveInterface*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ArchiveInterface> ice_connectionCached(bool __cached) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ArchiveInterface*>(_Base::ice_connectionCached(__cached).get());
    #else
        return dynamic_cast<ArchiveInterface*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ArchiveInterface> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ArchiveInterface*>(_Base::ice_endpointSelection(__est).get());
    #else
        return dynamic_cast<ArchiveInterface*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ArchiveInterface> ice_secure(bool __secure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ArchiveInterface*>(_Base::ice_secure(__secure).get());
    #else
        return dynamic_cast<ArchiveInterface*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ArchiveInterface> ice_preferSecure(bool __preferSecure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ArchiveInterface*>(_Base::ice_preferSecure(__preferSecure).get());
    #else
        return dynamic_cast<ArchiveInterface*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ArchiveInterface> ice_router(const ::Ice::RouterPrx& __router) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ArchiveInterface*>(_Base::ice_router(__router).get());
    #else
        return dynamic_cast<ArchiveInterface*>(::IceProxy::Ice::Object::ice_router(__router).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ArchiveInterface> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ArchiveInterface*>(_Base::ice_locator(__locator).get());
    #else
        return dynamic_cast<ArchiveInterface*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ArchiveInterface> ice_collocationOptimized(bool __co) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ArchiveInterface*>(_Base::ice_collocationOptimized(__co).get());
    #else
        return dynamic_cast<ArchiveInterface*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ArchiveInterface> ice_twoway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ArchiveInterface*>(_Base::ice_twoway().get());
    #else
        return dynamic_cast<ArchiveInterface*>(::IceProxy::Ice::Object::ice_twoway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ArchiveInterface> ice_oneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ArchiveInterface*>(_Base::ice_oneway().get());
    #else
        return dynamic_cast<ArchiveInterface*>(::IceProxy::Ice::Object::ice_oneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ArchiveInterface> ice_batchOneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ArchiveInterface*>(_Base::ice_batchOneway().get());
    #else
        return dynamic_cast<ArchiveInterface*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ArchiveInterface> ice_datagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ArchiveInterface*>(_Base::ice_datagram().get());
    #else
        return dynamic_cast<ArchiveInterface*>(::IceProxy::Ice::Object::ice_datagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ArchiveInterface> ice_batchDatagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ArchiveInterface*>(_Base::ice_batchDatagram().get());
    #else
        return dynamic_cast<ArchiveInterface*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ArchiveInterface> ice_compress(bool __compress) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ArchiveInterface*>(_Base::ice_compress(__compress).get());
    #else
        return dynamic_cast<ArchiveInterface*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ArchiveInterface> ice_timeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ArchiveInterface*>(_Base::ice_timeout(__timeout).get());
    #else
        return dynamic_cast<ArchiveInterface*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<ArchiveInterface> ice_connectionId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<ArchiveInterface*>(_Base::ice_connectionId(__id).get());
    #else
        return dynamic_cast<ArchiveInterface*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    #endif
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace iPlature
{

class ArchiveInterface : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void ArchiveL1OPC(const ::iPlature::TAGVALUEMAP&, const ::Ice::Context*) = 0;

    virtual void ArchiveMD(const ::iPlature::TAGVALUEMAP&, const ::iPlature::TAGVALUEMAP&, const ::std::string&, const ::Ice::Context*) = 0;

    virtual void ArchiveTimer(const ::iPlature::TAGNAMEARRAY&, const ::iPlature::TAGVALUEMAP&, const ::Ice::Context*) = 0;

    virtual void EnableArchive(bool, const ::iPlature::TAGNAMEARRAY&, const ::Ice::Context*) = 0;

    virtual void EnableAllArchives(bool, const ::Ice::Context*) = 0;

    virtual void RegisterTimerWatch(const ::std::string&, const ::iPlature::TAGNAMEARRAY&, ::Ice::Int, bool, const ::Ice::Context*) = 0;

    virtual void ReReadConfiguration(const ::Ice::Context*) = 0;
};

}

}

namespace IceDelegateM
{

namespace iPlature
{

class ArchiveInterface : virtual public ::IceDelegate::iPlature::ArchiveInterface,
                         virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void ArchiveL1OPC(const ::iPlature::TAGVALUEMAP&, const ::Ice::Context*);

    virtual void ArchiveMD(const ::iPlature::TAGVALUEMAP&, const ::iPlature::TAGVALUEMAP&, const ::std::string&, const ::Ice::Context*);

    virtual void ArchiveTimer(const ::iPlature::TAGNAMEARRAY&, const ::iPlature::TAGVALUEMAP&, const ::Ice::Context*);

    virtual void EnableArchive(bool, const ::iPlature::TAGNAMEARRAY&, const ::Ice::Context*);

    virtual void EnableAllArchives(bool, const ::Ice::Context*);

    virtual void RegisterTimerWatch(const ::std::string&, const ::iPlature::TAGNAMEARRAY&, ::Ice::Int, bool, const ::Ice::Context*);

    virtual void ReReadConfiguration(const ::Ice::Context*);
};

}

}

namespace IceDelegateD
{

namespace iPlature
{

class ArchiveInterface : virtual public ::IceDelegate::iPlature::ArchiveInterface,
                         virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void ArchiveL1OPC(const ::iPlature::TAGVALUEMAP&, const ::Ice::Context*);

    virtual void ArchiveMD(const ::iPlature::TAGVALUEMAP&, const ::iPlature::TAGVALUEMAP&, const ::std::string&, const ::Ice::Context*);

    virtual void ArchiveTimer(const ::iPlature::TAGNAMEARRAY&, const ::iPlature::TAGVALUEMAP&, const ::Ice::Context*);

    virtual void EnableArchive(bool, const ::iPlature::TAGNAMEARRAY&, const ::Ice::Context*);

    virtual void EnableAllArchives(bool, const ::Ice::Context*);

    virtual void RegisterTimerWatch(const ::std::string&, const ::iPlature::TAGNAMEARRAY&, ::Ice::Int, bool, const ::Ice::Context*);

    virtual void ReReadConfiguration(const ::Ice::Context*);
};

}

}

namespace iPlature
{

class ArchiveInterface : virtual public ::Ice::Object
{
public:

    typedef ArchiveInterfacePrx ProxyType;
    typedef ArchiveInterfacePtr PointerType;
    
    virtual ::Ice::ObjectPtr ice_clone() const;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void ArchiveL1OPC(const ::iPlature::TAGVALUEMAP&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___ArchiveL1OPC(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void ArchiveMD(const ::iPlature::TAGVALUEMAP&, const ::iPlature::TAGVALUEMAP&, const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___ArchiveMD(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void ArchiveTimer(const ::iPlature::TAGNAMEARRAY&, const ::iPlature::TAGVALUEMAP&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___ArchiveTimer(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void EnableArchive(bool, const ::iPlature::TAGNAMEARRAY&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___EnableArchive(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void EnableAllArchives(bool, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___EnableAllArchives(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void RegisterTimerWatch(const ::std::string&, const ::iPlature::TAGNAMEARRAY&, ::Ice::Int, bool, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___RegisterTimerWatch(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void ReReadConfiguration(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___ReReadConfiguration(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void __write(::IceInternal::BasicStream*) const;
    virtual void __read(::IceInternal::BasicStream*, bool);
// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
    virtual void __write(const ::Ice::OutputStreamPtr&) const;
    virtual void __read(const ::Ice::InputStreamPtr&, bool);
#endif
};

inline bool operator==(const ArchiveInterface& l, const ArchiveInterface& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const ArchiveInterface& l, const ArchiveInterface& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace iPlature
{

template<class T>
class CallbackNC_ArchiveInterface_ArchiveL1OPC : public Callback_ArchiveInterface_ArchiveL1OPC_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_ArchiveInterface_ArchiveL1OPC(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_ArchiveInterface_ArchiveL1OPCPtr
newCallback_ArchiveInterface_ArchiveL1OPC(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_ArchiveL1OPC<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ArchiveInterface_ArchiveL1OPCPtr
newCallback_ArchiveInterface_ArchiveL1OPC(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_ArchiveL1OPC<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_ArchiveInterface_ArchiveL1OPCPtr
newCallback_ArchiveInterface_ArchiveL1OPC(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_ArchiveL1OPC<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ArchiveInterface_ArchiveL1OPCPtr
newCallback_ArchiveInterface_ArchiveL1OPC(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_ArchiveL1OPC<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_ArchiveInterface_ArchiveL1OPC : public Callback_ArchiveInterface_ArchiveL1OPC_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_ArchiveInterface_ArchiveL1OPC(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_ArchiveInterface_ArchiveL1OPCPtr
newCallback_ArchiveInterface_ArchiveL1OPC(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_ArchiveL1OPC<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ArchiveInterface_ArchiveL1OPCPtr
newCallback_ArchiveInterface_ArchiveL1OPC(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_ArchiveL1OPC<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_ArchiveInterface_ArchiveL1OPCPtr
newCallback_ArchiveInterface_ArchiveL1OPC(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_ArchiveL1OPC<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ArchiveInterface_ArchiveL1OPCPtr
newCallback_ArchiveInterface_ArchiveL1OPC(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_ArchiveL1OPC<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_ArchiveInterface_ArchiveMD : public Callback_ArchiveInterface_ArchiveMD_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_ArchiveInterface_ArchiveMD(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_ArchiveInterface_ArchiveMDPtr
newCallback_ArchiveInterface_ArchiveMD(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_ArchiveMD<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ArchiveInterface_ArchiveMDPtr
newCallback_ArchiveInterface_ArchiveMD(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_ArchiveMD<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_ArchiveInterface_ArchiveMDPtr
newCallback_ArchiveInterface_ArchiveMD(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_ArchiveMD<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ArchiveInterface_ArchiveMDPtr
newCallback_ArchiveInterface_ArchiveMD(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_ArchiveMD<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_ArchiveInterface_ArchiveMD : public Callback_ArchiveInterface_ArchiveMD_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_ArchiveInterface_ArchiveMD(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_ArchiveInterface_ArchiveMDPtr
newCallback_ArchiveInterface_ArchiveMD(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_ArchiveMD<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ArchiveInterface_ArchiveMDPtr
newCallback_ArchiveInterface_ArchiveMD(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_ArchiveMD<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_ArchiveInterface_ArchiveMDPtr
newCallback_ArchiveInterface_ArchiveMD(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_ArchiveMD<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ArchiveInterface_ArchiveMDPtr
newCallback_ArchiveInterface_ArchiveMD(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_ArchiveMD<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_ArchiveInterface_ArchiveTimer : public Callback_ArchiveInterface_ArchiveTimer_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_ArchiveInterface_ArchiveTimer(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_ArchiveInterface_ArchiveTimerPtr
newCallback_ArchiveInterface_ArchiveTimer(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_ArchiveTimer<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ArchiveInterface_ArchiveTimerPtr
newCallback_ArchiveInterface_ArchiveTimer(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_ArchiveTimer<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_ArchiveInterface_ArchiveTimerPtr
newCallback_ArchiveInterface_ArchiveTimer(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_ArchiveTimer<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ArchiveInterface_ArchiveTimerPtr
newCallback_ArchiveInterface_ArchiveTimer(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_ArchiveTimer<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_ArchiveInterface_ArchiveTimer : public Callback_ArchiveInterface_ArchiveTimer_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_ArchiveInterface_ArchiveTimer(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_ArchiveInterface_ArchiveTimerPtr
newCallback_ArchiveInterface_ArchiveTimer(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_ArchiveTimer<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ArchiveInterface_ArchiveTimerPtr
newCallback_ArchiveInterface_ArchiveTimer(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_ArchiveTimer<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_ArchiveInterface_ArchiveTimerPtr
newCallback_ArchiveInterface_ArchiveTimer(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_ArchiveTimer<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ArchiveInterface_ArchiveTimerPtr
newCallback_ArchiveInterface_ArchiveTimer(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_ArchiveTimer<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_ArchiveInterface_EnableArchive : public Callback_ArchiveInterface_EnableArchive_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_ArchiveInterface_EnableArchive(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_ArchiveInterface_EnableArchivePtr
newCallback_ArchiveInterface_EnableArchive(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_EnableArchive<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ArchiveInterface_EnableArchivePtr
newCallback_ArchiveInterface_EnableArchive(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_EnableArchive<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_ArchiveInterface_EnableArchivePtr
newCallback_ArchiveInterface_EnableArchive(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_EnableArchive<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ArchiveInterface_EnableArchivePtr
newCallback_ArchiveInterface_EnableArchive(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_EnableArchive<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_ArchiveInterface_EnableArchive : public Callback_ArchiveInterface_EnableArchive_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_ArchiveInterface_EnableArchive(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_ArchiveInterface_EnableArchivePtr
newCallback_ArchiveInterface_EnableArchive(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_EnableArchive<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ArchiveInterface_EnableArchivePtr
newCallback_ArchiveInterface_EnableArchive(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_EnableArchive<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_ArchiveInterface_EnableArchivePtr
newCallback_ArchiveInterface_EnableArchive(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_EnableArchive<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ArchiveInterface_EnableArchivePtr
newCallback_ArchiveInterface_EnableArchive(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_EnableArchive<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_ArchiveInterface_EnableAllArchives : public Callback_ArchiveInterface_EnableAllArchives_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_ArchiveInterface_EnableAllArchives(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_ArchiveInterface_EnableAllArchivesPtr
newCallback_ArchiveInterface_EnableAllArchives(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_EnableAllArchives<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ArchiveInterface_EnableAllArchivesPtr
newCallback_ArchiveInterface_EnableAllArchives(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_EnableAllArchives<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_ArchiveInterface_EnableAllArchivesPtr
newCallback_ArchiveInterface_EnableAllArchives(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_EnableAllArchives<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ArchiveInterface_EnableAllArchivesPtr
newCallback_ArchiveInterface_EnableAllArchives(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_EnableAllArchives<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_ArchiveInterface_EnableAllArchives : public Callback_ArchiveInterface_EnableAllArchives_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_ArchiveInterface_EnableAllArchives(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_ArchiveInterface_EnableAllArchivesPtr
newCallback_ArchiveInterface_EnableAllArchives(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_EnableAllArchives<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ArchiveInterface_EnableAllArchivesPtr
newCallback_ArchiveInterface_EnableAllArchives(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_EnableAllArchives<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_ArchiveInterface_EnableAllArchivesPtr
newCallback_ArchiveInterface_EnableAllArchives(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_EnableAllArchives<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ArchiveInterface_EnableAllArchivesPtr
newCallback_ArchiveInterface_EnableAllArchives(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_EnableAllArchives<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_ArchiveInterface_RegisterTimerWatch : public Callback_ArchiveInterface_RegisterTimerWatch_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_ArchiveInterface_RegisterTimerWatch(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_ArchiveInterface_RegisterTimerWatchPtr
newCallback_ArchiveInterface_RegisterTimerWatch(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_RegisterTimerWatch<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ArchiveInterface_RegisterTimerWatchPtr
newCallback_ArchiveInterface_RegisterTimerWatch(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_RegisterTimerWatch<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_ArchiveInterface_RegisterTimerWatchPtr
newCallback_ArchiveInterface_RegisterTimerWatch(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_RegisterTimerWatch<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ArchiveInterface_RegisterTimerWatchPtr
newCallback_ArchiveInterface_RegisterTimerWatch(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_RegisterTimerWatch<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_ArchiveInterface_RegisterTimerWatch : public Callback_ArchiveInterface_RegisterTimerWatch_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_ArchiveInterface_RegisterTimerWatch(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_ArchiveInterface_RegisterTimerWatchPtr
newCallback_ArchiveInterface_RegisterTimerWatch(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_RegisterTimerWatch<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ArchiveInterface_RegisterTimerWatchPtr
newCallback_ArchiveInterface_RegisterTimerWatch(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_RegisterTimerWatch<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_ArchiveInterface_RegisterTimerWatchPtr
newCallback_ArchiveInterface_RegisterTimerWatch(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_RegisterTimerWatch<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ArchiveInterface_RegisterTimerWatchPtr
newCallback_ArchiveInterface_RegisterTimerWatch(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_RegisterTimerWatch<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_ArchiveInterface_ReReadConfiguration : public Callback_ArchiveInterface_ReReadConfiguration_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_ArchiveInterface_ReReadConfiguration(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_ArchiveInterface_ReReadConfigurationPtr
newCallback_ArchiveInterface_ReReadConfiguration(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_ReReadConfiguration<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ArchiveInterface_ReReadConfigurationPtr
newCallback_ArchiveInterface_ReReadConfiguration(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_ReReadConfiguration<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_ArchiveInterface_ReReadConfigurationPtr
newCallback_ArchiveInterface_ReReadConfiguration(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_ReReadConfiguration<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ArchiveInterface_ReReadConfigurationPtr
newCallback_ArchiveInterface_ReReadConfiguration(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ArchiveInterface_ReReadConfiguration<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_ArchiveInterface_ReReadConfiguration : public Callback_ArchiveInterface_ReReadConfiguration_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_ArchiveInterface_ReReadConfiguration(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_ArchiveInterface_ReReadConfigurationPtr
newCallback_ArchiveInterface_ReReadConfiguration(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_ReReadConfiguration<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ArchiveInterface_ReReadConfigurationPtr
newCallback_ArchiveInterface_ReReadConfiguration(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_ReReadConfiguration<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_ArchiveInterface_ReReadConfigurationPtr
newCallback_ArchiveInterface_ReReadConfiguration(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_ReReadConfiguration<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ArchiveInterface_ReReadConfigurationPtr
newCallback_ArchiveInterface_ReReadConfiguration(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ArchiveInterface_ReReadConfiguration<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
