// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

// <auto-generated>
//
// Generated from file `Communicator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>

#ifndef __Communicator_h__
#define __Communicator_h__

#include <Ice/LocalObjectF.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace iPlature
{

class Communicator;

}

}

namespace iPlature
{

class Communicator;
bool operator==(const Communicator&, const Communicator&);
bool operator<(const Communicator&, const Communicator&);

}

namespace IceInternal
{

::Ice::Object* upCast(::iPlature::Communicator*);
::IceProxy::Ice::Object* upCast(::IceProxy::iPlature::Communicator*);

}

namespace iPlature
{

typedef ::IceInternal::Handle< ::iPlature::Communicator> CommunicatorPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::iPlature::Communicator> CommunicatorPrx;

void __read(::IceInternal::BasicStream*, CommunicatorPrx&);
void __patch__CommunicatorPtr(void*, ::Ice::ObjectPtr&);

}

namespace iPlature
{

typedef ::std::map< ::std::string, ::std::string> Parameters;
void __writeParameters(::IceInternal::BasicStream*, const Parameters&);
void __readParameters(::IceInternal::BasicStream*, Parameters&);

typedef ::std::vector< ::Ice::Byte> ByteSeq;

}

namespace iPlature
{

class Callback_Communicator_CallNetService_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Communicator_CallNetService_Base> Callback_Communicator_CallNetServicePtr;

class Callback_Communicator_CallNetServiceP_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Communicator_CallNetServiceP_Base> Callback_Communicator_CallNetServicePPtr;

class Callback_Communicator_CallNetServiceMsg_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Communicator_CallNetServiceMsg_Base> Callback_Communicator_CallNetServiceMsgPtr;

class Callback_Communicator_CallNetServicePMsg_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Communicator_CallNetServicePMsg_Base> Callback_Communicator_CallNetServicePMsgPtr;

}

namespace IceProxy
{

namespace iPlature
{

class Communicator : virtual public ::IceProxy::Ice::Object
{
public:

    void CallNetService(const ::std::string& serviceName, const ::std::string& operation, const ::iPlature::ByteSeq& byteArray)
    {
        CallNetService(serviceName, operation, byteArray, 0);
    }
    void CallNetService(const ::std::string& serviceName, const ::std::string& operation, const ::iPlature::ByteSeq& byteArray, const ::Ice::Context& __ctx)
    {
        CallNetService(serviceName, operation, byteArray, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_CallNetService(const ::std::string& serviceName, const ::std::string& operation, const ::iPlature::ByteSeq& byteArray)
    {
        return begin_CallNetService(serviceName, operation, byteArray, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_CallNetService(const ::std::string& serviceName, const ::std::string& operation, const ::iPlature::ByteSeq& byteArray, const ::Ice::Context& __ctx)
    {
        return begin_CallNetService(serviceName, operation, byteArray, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_CallNetService(const ::std::string& serviceName, const ::std::string& operation, const ::iPlature::ByteSeq& byteArray, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_CallNetService(serviceName, operation, byteArray, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_CallNetService(const ::std::string& serviceName, const ::std::string& operation, const ::iPlature::ByteSeq& byteArray, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_CallNetService(serviceName, operation, byteArray, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_CallNetService(const ::std::string& serviceName, const ::std::string& operation, const ::iPlature::ByteSeq& byteArray, const ::iPlature::Callback_Communicator_CallNetServicePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_CallNetService(serviceName, operation, byteArray, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_CallNetService(const ::std::string& serviceName, const ::std::string& operation, const ::iPlature::ByteSeq& byteArray, const ::Ice::Context& __ctx, const ::iPlature::Callback_Communicator_CallNetServicePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_CallNetService(serviceName, operation, byteArray, &__ctx, __del, __cookie);
    }

    void end_CallNetService(const ::Ice::AsyncResultPtr&);
    
private:

    void CallNetService(const ::std::string&, const ::std::string&, const ::iPlature::ByteSeq&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_CallNetService(const ::std::string&, const ::std::string&, const ::iPlature::ByteSeq&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void CallNetServiceP(const ::std::string& serviceName, const ::std::string& operation, const ::iPlature::Parameters& param, const ::iPlature::ByteSeq& byteArray)
    {
        CallNetServiceP(serviceName, operation, param, byteArray, 0);
    }
    void CallNetServiceP(const ::std::string& serviceName, const ::std::string& operation, const ::iPlature::Parameters& param, const ::iPlature::ByteSeq& byteArray, const ::Ice::Context& __ctx)
    {
        CallNetServiceP(serviceName, operation, param, byteArray, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_CallNetServiceP(const ::std::string& serviceName, const ::std::string& operation, const ::iPlature::Parameters& param, const ::iPlature::ByteSeq& byteArray)
    {
        return begin_CallNetServiceP(serviceName, operation, param, byteArray, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_CallNetServiceP(const ::std::string& serviceName, const ::std::string& operation, const ::iPlature::Parameters& param, const ::iPlature::ByteSeq& byteArray, const ::Ice::Context& __ctx)
    {
        return begin_CallNetServiceP(serviceName, operation, param, byteArray, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_CallNetServiceP(const ::std::string& serviceName, const ::std::string& operation, const ::iPlature::Parameters& param, const ::iPlature::ByteSeq& byteArray, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_CallNetServiceP(serviceName, operation, param, byteArray, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_CallNetServiceP(const ::std::string& serviceName, const ::std::string& operation, const ::iPlature::Parameters& param, const ::iPlature::ByteSeq& byteArray, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_CallNetServiceP(serviceName, operation, param, byteArray, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_CallNetServiceP(const ::std::string& serviceName, const ::std::string& operation, const ::iPlature::Parameters& param, const ::iPlature::ByteSeq& byteArray, const ::iPlature::Callback_Communicator_CallNetServicePPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_CallNetServiceP(serviceName, operation, param, byteArray, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_CallNetServiceP(const ::std::string& serviceName, const ::std::string& operation, const ::iPlature::Parameters& param, const ::iPlature::ByteSeq& byteArray, const ::Ice::Context& __ctx, const ::iPlature::Callback_Communicator_CallNetServicePPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_CallNetServiceP(serviceName, operation, param, byteArray, &__ctx, __del, __cookie);
    }

    void end_CallNetServiceP(const ::Ice::AsyncResultPtr&);
    
private:

    void CallNetServiceP(const ::std::string&, const ::std::string&, const ::iPlature::Parameters&, const ::iPlature::ByteSeq&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_CallNetServiceP(const ::std::string&, const ::std::string&, const ::iPlature::Parameters&, const ::iPlature::ByteSeq&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void CallNetServiceMsg(const ::std::string& serviceName, const ::std::string& operation, const ::std::string& msgName, const ::iPlature::ByteSeq& byteArray)
    {
        CallNetServiceMsg(serviceName, operation, msgName, byteArray, 0);
    }
    void CallNetServiceMsg(const ::std::string& serviceName, const ::std::string& operation, const ::std::string& msgName, const ::iPlature::ByteSeq& byteArray, const ::Ice::Context& __ctx)
    {
        CallNetServiceMsg(serviceName, operation, msgName, byteArray, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_CallNetServiceMsg(const ::std::string& serviceName, const ::std::string& operation, const ::std::string& msgName, const ::iPlature::ByteSeq& byteArray)
    {
        return begin_CallNetServiceMsg(serviceName, operation, msgName, byteArray, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_CallNetServiceMsg(const ::std::string& serviceName, const ::std::string& operation, const ::std::string& msgName, const ::iPlature::ByteSeq& byteArray, const ::Ice::Context& __ctx)
    {
        return begin_CallNetServiceMsg(serviceName, operation, msgName, byteArray, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_CallNetServiceMsg(const ::std::string& serviceName, const ::std::string& operation, const ::std::string& msgName, const ::iPlature::ByteSeq& byteArray, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_CallNetServiceMsg(serviceName, operation, msgName, byteArray, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_CallNetServiceMsg(const ::std::string& serviceName, const ::std::string& operation, const ::std::string& msgName, const ::iPlature::ByteSeq& byteArray, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_CallNetServiceMsg(serviceName, operation, msgName, byteArray, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_CallNetServiceMsg(const ::std::string& serviceName, const ::std::string& operation, const ::std::string& msgName, const ::iPlature::ByteSeq& byteArray, const ::iPlature::Callback_Communicator_CallNetServiceMsgPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_CallNetServiceMsg(serviceName, operation, msgName, byteArray, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_CallNetServiceMsg(const ::std::string& serviceName, const ::std::string& operation, const ::std::string& msgName, const ::iPlature::ByteSeq& byteArray, const ::Ice::Context& __ctx, const ::iPlature::Callback_Communicator_CallNetServiceMsgPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_CallNetServiceMsg(serviceName, operation, msgName, byteArray, &__ctx, __del, __cookie);
    }

    void end_CallNetServiceMsg(const ::Ice::AsyncResultPtr&);
    
private:

    void CallNetServiceMsg(const ::std::string&, const ::std::string&, const ::std::string&, const ::iPlature::ByteSeq&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_CallNetServiceMsg(const ::std::string&, const ::std::string&, const ::std::string&, const ::iPlature::ByteSeq&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void CallNetServicePMsg(const ::std::string& serviceName, const ::std::string& operation, const ::std::string& msgName, const ::iPlature::Parameters& param, const ::iPlature::ByteSeq& byteArray)
    {
        CallNetServicePMsg(serviceName, operation, msgName, param, byteArray, 0);
    }
    void CallNetServicePMsg(const ::std::string& serviceName, const ::std::string& operation, const ::std::string& msgName, const ::iPlature::Parameters& param, const ::iPlature::ByteSeq& byteArray, const ::Ice::Context& __ctx)
    {
        CallNetServicePMsg(serviceName, operation, msgName, param, byteArray, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_CallNetServicePMsg(const ::std::string& serviceName, const ::std::string& operation, const ::std::string& msgName, const ::iPlature::Parameters& param, const ::iPlature::ByteSeq& byteArray)
    {
        return begin_CallNetServicePMsg(serviceName, operation, msgName, param, byteArray, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_CallNetServicePMsg(const ::std::string& serviceName, const ::std::string& operation, const ::std::string& msgName, const ::iPlature::Parameters& param, const ::iPlature::ByteSeq& byteArray, const ::Ice::Context& __ctx)
    {
        return begin_CallNetServicePMsg(serviceName, operation, msgName, param, byteArray, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_CallNetServicePMsg(const ::std::string& serviceName, const ::std::string& operation, const ::std::string& msgName, const ::iPlature::Parameters& param, const ::iPlature::ByteSeq& byteArray, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_CallNetServicePMsg(serviceName, operation, msgName, param, byteArray, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_CallNetServicePMsg(const ::std::string& serviceName, const ::std::string& operation, const ::std::string& msgName, const ::iPlature::Parameters& param, const ::iPlature::ByteSeq& byteArray, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_CallNetServicePMsg(serviceName, operation, msgName, param, byteArray, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_CallNetServicePMsg(const ::std::string& serviceName, const ::std::string& operation, const ::std::string& msgName, const ::iPlature::Parameters& param, const ::iPlature::ByteSeq& byteArray, const ::iPlature::Callback_Communicator_CallNetServicePMsgPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_CallNetServicePMsg(serviceName, operation, msgName, param, byteArray, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_CallNetServicePMsg(const ::std::string& serviceName, const ::std::string& operation, const ::std::string& msgName, const ::iPlature::Parameters& param, const ::iPlature::ByteSeq& byteArray, const ::Ice::Context& __ctx, const ::iPlature::Callback_Communicator_CallNetServicePMsgPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_CallNetServicePMsg(serviceName, operation, msgName, param, byteArray, &__ctx, __del, __cookie);
    }

    void end_CallNetServicePMsg(const ::Ice::AsyncResultPtr&);
    
private:

    void CallNetServicePMsg(const ::std::string&, const ::std::string&, const ::std::string&, const ::iPlature::Parameters&, const ::iPlature::ByteSeq&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_CallNetServicePMsg(const ::std::string&, const ::std::string&, const ::std::string&, const ::iPlature::Parameters&, const ::iPlature::ByteSeq&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<Communicator> ice_context(const ::Ice::Context& __context) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Communicator*>(_Base::ice_context(__context).get());
    #else
        return dynamic_cast<Communicator*>(::IceProxy::Ice::Object::ice_context(__context).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Communicator> ice_adapterId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Communicator*>(_Base::ice_adapterId(__id).get());
    #else
        return dynamic_cast<Communicator*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Communicator> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Communicator*>(_Base::ice_endpoints(__endpoints).get());
    #else
        return dynamic_cast<Communicator*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Communicator> ice_locatorCacheTimeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Communicator*>(_Base::ice_locatorCacheTimeout(__timeout).get());
    #else
        return dynamic_cast<Communicator*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Communicator> ice_connectionCached(bool __cached) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Communicator*>(_Base::ice_connectionCached(__cached).get());
    #else
        return dynamic_cast<Communicator*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Communicator> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Communicator*>(_Base::ice_endpointSelection(__est).get());
    #else
        return dynamic_cast<Communicator*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Communicator> ice_secure(bool __secure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Communicator*>(_Base::ice_secure(__secure).get());
    #else
        return dynamic_cast<Communicator*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Communicator> ice_preferSecure(bool __preferSecure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Communicator*>(_Base::ice_preferSecure(__preferSecure).get());
    #else
        return dynamic_cast<Communicator*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Communicator> ice_router(const ::Ice::RouterPrx& __router) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Communicator*>(_Base::ice_router(__router).get());
    #else
        return dynamic_cast<Communicator*>(::IceProxy::Ice::Object::ice_router(__router).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Communicator> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Communicator*>(_Base::ice_locator(__locator).get());
    #else
        return dynamic_cast<Communicator*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Communicator> ice_collocationOptimized(bool __co) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Communicator*>(_Base::ice_collocationOptimized(__co).get());
    #else
        return dynamic_cast<Communicator*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Communicator> ice_twoway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Communicator*>(_Base::ice_twoway().get());
    #else
        return dynamic_cast<Communicator*>(::IceProxy::Ice::Object::ice_twoway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Communicator> ice_oneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Communicator*>(_Base::ice_oneway().get());
    #else
        return dynamic_cast<Communicator*>(::IceProxy::Ice::Object::ice_oneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Communicator> ice_batchOneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Communicator*>(_Base::ice_batchOneway().get());
    #else
        return dynamic_cast<Communicator*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Communicator> ice_datagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Communicator*>(_Base::ice_datagram().get());
    #else
        return dynamic_cast<Communicator*>(::IceProxy::Ice::Object::ice_datagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Communicator> ice_batchDatagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Communicator*>(_Base::ice_batchDatagram().get());
    #else
        return dynamic_cast<Communicator*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Communicator> ice_compress(bool __compress) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Communicator*>(_Base::ice_compress(__compress).get());
    #else
        return dynamic_cast<Communicator*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Communicator> ice_timeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Communicator*>(_Base::ice_timeout(__timeout).get());
    #else
        return dynamic_cast<Communicator*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Communicator> ice_connectionId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Communicator*>(_Base::ice_connectionId(__id).get());
    #else
        return dynamic_cast<Communicator*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    #endif
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace iPlature
{

class Communicator : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void CallNetService(const ::std::string&, const ::std::string&, const ::iPlature::ByteSeq&, const ::Ice::Context*) = 0;

    virtual void CallNetServiceP(const ::std::string&, const ::std::string&, const ::iPlature::Parameters&, const ::iPlature::ByteSeq&, const ::Ice::Context*) = 0;

    virtual void CallNetServiceMsg(const ::std::string&, const ::std::string&, const ::std::string&, const ::iPlature::ByteSeq&, const ::Ice::Context*) = 0;

    virtual void CallNetServicePMsg(const ::std::string&, const ::std::string&, const ::std::string&, const ::iPlature::Parameters&, const ::iPlature::ByteSeq&, const ::Ice::Context*) = 0;
};

}

}

namespace IceDelegateM
{

namespace iPlature
{

class Communicator : virtual public ::IceDelegate::iPlature::Communicator,
                     virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void CallNetService(const ::std::string&, const ::std::string&, const ::iPlature::ByteSeq&, const ::Ice::Context*);

    virtual void CallNetServiceP(const ::std::string&, const ::std::string&, const ::iPlature::Parameters&, const ::iPlature::ByteSeq&, const ::Ice::Context*);

    virtual void CallNetServiceMsg(const ::std::string&, const ::std::string&, const ::std::string&, const ::iPlature::ByteSeq&, const ::Ice::Context*);

    virtual void CallNetServicePMsg(const ::std::string&, const ::std::string&, const ::std::string&, const ::iPlature::Parameters&, const ::iPlature::ByteSeq&, const ::Ice::Context*);
};

}

}

namespace IceDelegateD
{

namespace iPlature
{

class Communicator : virtual public ::IceDelegate::iPlature::Communicator,
                     virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void CallNetService(const ::std::string&, const ::std::string&, const ::iPlature::ByteSeq&, const ::Ice::Context*);

    virtual void CallNetServiceP(const ::std::string&, const ::std::string&, const ::iPlature::Parameters&, const ::iPlature::ByteSeq&, const ::Ice::Context*);

    virtual void CallNetServiceMsg(const ::std::string&, const ::std::string&, const ::std::string&, const ::iPlature::ByteSeq&, const ::Ice::Context*);

    virtual void CallNetServicePMsg(const ::std::string&, const ::std::string&, const ::std::string&, const ::iPlature::Parameters&, const ::iPlature::ByteSeq&, const ::Ice::Context*);
};

}

}

namespace iPlature
{

class Communicator : virtual public ::Ice::Object
{
public:

    typedef CommunicatorPrx ProxyType;
    typedef CommunicatorPtr PointerType;
    
    virtual ::Ice::ObjectPtr ice_clone() const;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void CallNetService(const ::std::string&, const ::std::string&, const ::iPlature::ByteSeq&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___CallNetService(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void CallNetServiceP(const ::std::string&, const ::std::string&, const ::iPlature::Parameters&, const ::iPlature::ByteSeq&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___CallNetServiceP(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void CallNetServiceMsg(const ::std::string&, const ::std::string&, const ::std::string&, const ::iPlature::ByteSeq&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___CallNetServiceMsg(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void CallNetServicePMsg(const ::std::string&, const ::std::string&, const ::std::string&, const ::iPlature::Parameters&, const ::iPlature::ByteSeq&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___CallNetServicePMsg(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void __write(::IceInternal::BasicStream*) const;
    virtual void __read(::IceInternal::BasicStream*, bool);
// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
    virtual void __write(const ::Ice::OutputStreamPtr&) const;
    virtual void __read(const ::Ice::InputStreamPtr&, bool);
#endif
};

inline bool operator==(const Communicator& l, const Communicator& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const Communicator& l, const Communicator& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace iPlature
{

template<class T>
class CallbackNC_Communicator_CallNetService : public Callback_Communicator_CallNetService_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Communicator_CallNetService(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Communicator_CallNetServicePtr
newCallback_Communicator_CallNetService(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Communicator_CallNetService<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Communicator_CallNetServicePtr
newCallback_Communicator_CallNetService(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Communicator_CallNetService<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Communicator_CallNetServicePtr
newCallback_Communicator_CallNetService(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Communicator_CallNetService<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Communicator_CallNetServicePtr
newCallback_Communicator_CallNetService(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Communicator_CallNetService<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Communicator_CallNetService : public Callback_Communicator_CallNetService_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Communicator_CallNetService(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Communicator_CallNetServicePtr
newCallback_Communicator_CallNetService(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Communicator_CallNetService<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Communicator_CallNetServicePtr
newCallback_Communicator_CallNetService(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Communicator_CallNetService<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Communicator_CallNetServicePtr
newCallback_Communicator_CallNetService(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Communicator_CallNetService<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Communicator_CallNetServicePtr
newCallback_Communicator_CallNetService(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Communicator_CallNetService<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_Communicator_CallNetServiceP : public Callback_Communicator_CallNetServiceP_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Communicator_CallNetServiceP(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Communicator_CallNetServicePPtr
newCallback_Communicator_CallNetServiceP(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Communicator_CallNetServiceP<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Communicator_CallNetServicePPtr
newCallback_Communicator_CallNetServiceP(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Communicator_CallNetServiceP<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Communicator_CallNetServicePPtr
newCallback_Communicator_CallNetServiceP(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Communicator_CallNetServiceP<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Communicator_CallNetServicePPtr
newCallback_Communicator_CallNetServiceP(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Communicator_CallNetServiceP<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Communicator_CallNetServiceP : public Callback_Communicator_CallNetServiceP_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Communicator_CallNetServiceP(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Communicator_CallNetServicePPtr
newCallback_Communicator_CallNetServiceP(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Communicator_CallNetServiceP<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Communicator_CallNetServicePPtr
newCallback_Communicator_CallNetServiceP(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Communicator_CallNetServiceP<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Communicator_CallNetServicePPtr
newCallback_Communicator_CallNetServiceP(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Communicator_CallNetServiceP<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Communicator_CallNetServicePPtr
newCallback_Communicator_CallNetServiceP(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Communicator_CallNetServiceP<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_Communicator_CallNetServiceMsg : public Callback_Communicator_CallNetServiceMsg_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Communicator_CallNetServiceMsg(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Communicator_CallNetServiceMsgPtr
newCallback_Communicator_CallNetServiceMsg(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Communicator_CallNetServiceMsg<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Communicator_CallNetServiceMsgPtr
newCallback_Communicator_CallNetServiceMsg(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Communicator_CallNetServiceMsg<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Communicator_CallNetServiceMsgPtr
newCallback_Communicator_CallNetServiceMsg(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Communicator_CallNetServiceMsg<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Communicator_CallNetServiceMsgPtr
newCallback_Communicator_CallNetServiceMsg(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Communicator_CallNetServiceMsg<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Communicator_CallNetServiceMsg : public Callback_Communicator_CallNetServiceMsg_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Communicator_CallNetServiceMsg(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Communicator_CallNetServiceMsgPtr
newCallback_Communicator_CallNetServiceMsg(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Communicator_CallNetServiceMsg<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Communicator_CallNetServiceMsgPtr
newCallback_Communicator_CallNetServiceMsg(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Communicator_CallNetServiceMsg<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Communicator_CallNetServiceMsgPtr
newCallback_Communicator_CallNetServiceMsg(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Communicator_CallNetServiceMsg<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Communicator_CallNetServiceMsgPtr
newCallback_Communicator_CallNetServiceMsg(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Communicator_CallNetServiceMsg<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_Communicator_CallNetServicePMsg : public Callback_Communicator_CallNetServicePMsg_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Communicator_CallNetServicePMsg(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Communicator_CallNetServicePMsgPtr
newCallback_Communicator_CallNetServicePMsg(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Communicator_CallNetServicePMsg<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Communicator_CallNetServicePMsgPtr
newCallback_Communicator_CallNetServicePMsg(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Communicator_CallNetServicePMsg<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Communicator_CallNetServicePMsgPtr
newCallback_Communicator_CallNetServicePMsg(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Communicator_CallNetServicePMsg<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Communicator_CallNetServicePMsgPtr
newCallback_Communicator_CallNetServicePMsg(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Communicator_CallNetServicePMsg<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Communicator_CallNetServicePMsg : public Callback_Communicator_CallNetServicePMsg_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Communicator_CallNetServicePMsg(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Communicator_CallNetServicePMsgPtr
newCallback_Communicator_CallNetServicePMsg(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Communicator_CallNetServicePMsg<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Communicator_CallNetServicePMsgPtr
newCallback_Communicator_CallNetServicePMsg(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Communicator_CallNetServicePMsg<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Communicator_CallNetServicePMsgPtr
newCallback_Communicator_CallNetServicePMsg(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Communicator_CallNetServicePMsg<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Communicator_CallNetServicePMsgPtr
newCallback_Communicator_CallNetServicePMsg(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Communicator_CallNetServicePMsg<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
