top_srcdir = ${IPLATURE}

PROGRAM   :=  ../../../Bin/APP_RGV
SRCDIRS   := .
include ../../../Script/iplature_exegeneral 
CXXFLAGS  +=  -I. -I../../../Include/CommonH -I../../../Include/json
LINKWITH  +=  -L ../../../Library/json -ljson 

