// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

// <auto-generated>
//
// Generated from file `EvictorF.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>

#ifndef __Freeze_EvictorF_h__
#define __Freeze_EvictorF_h__

#include <Ice/LocalObjectF.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

#ifndef FREEZE_API
#   ifdef FREEZE_API_EXPORTS
#       define FREEZE_API ICE_DECLSPEC_EXPORT
#   else
#       define FREEZE_API ICE_DECLSPEC_IMPORT
#   endif
#endif

namespace Freeze
{

class ServantInitializer;
bool operator==(const ServantInitializer&, const ServantInitializer&);
bool operator<(const ServantInitializer&, const ServantInitializer&);

class BackgroundSaveEvictor;
bool operator==(const BackgroundSaveEvictor&, const BackgroundSaveEvictor&);
bool operator<(const BackgroundSaveEvictor&, const BackgroundSaveEvictor&);

class TransactionalEvictor;
bool operator==(const TransactionalEvictor&, const TransactionalEvictor&);
bool operator<(const TransactionalEvictor&, const TransactionalEvictor&);

}

namespace IceInternal
{

FREEZE_API ::Ice::LocalObject* upCast(::Freeze::ServantInitializer*);

FREEZE_API ::Ice::LocalObject* upCast(::Freeze::BackgroundSaveEvictor*);

FREEZE_API ::Ice::LocalObject* upCast(::Freeze::TransactionalEvictor*);

}

namespace Freeze
{

typedef ::IceInternal::Handle< ::Freeze::ServantInitializer> ServantInitializerPtr;

typedef ::IceInternal::Handle< ::Freeze::BackgroundSaveEvictor> BackgroundSaveEvictorPtr;

typedef ::IceInternal::Handle< ::Freeze::TransactionalEvictor> TransactionalEvictorPtr;

}

#endif
